name: Docker CI/CD Practice

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test -- --watch=false --passWithNoTests --forceExit

      - name: Build Docker Image
        run: docker build -t my-node-app .

      - name: Run Docker Container
        run: |
          docker run -d \
            --name my-node-app \
            -p 3000:3000 \
            my-node-app

      - name: Check Container
        run: docker ps

      - name: Test Application
        run: |
          sleep 5
          curl http://localhost:3000

      - name: Container Logs
        if: always()
        run: docker logs my-node-app


      # Cleanup